/* Channel mod by USS_Shenzhou -- GPL-3.0 */
package cn.ussshenzhou.channel.audio.nativ;
public enum NvAFX_Status {
    NVAFX_STATUS_SUCCESS,
    NVAFX_STATUS_FAILED,
    NVAFX_STATUS_INVALID_HANDLE,
    NVAFX_STATUS_INVALID_PARAM,
    NVAFX_STATUS_IMMUTABLE_PARAM,
    NVAFX_STATUS_INSUFFICIENT_DATA,
    NVAFX_STATUS_EFFECT_NOT_AVAILABLE,
    NVAFX_STATUS_OUTPUT_BUFFER_TOO_SMALL,
    NVAFX_STATUS_MODEL_LOAD_FAILED,
    NVAFX_STATUS_32_SERVER_NOT_REGISTERED,
    NVAFX_STATUS_32_COM_ERROR,
    NVAFX_STATUS_GPU_UNSUPPORTED,
    NVAFX_STATUS_CUDA_CONTEXT_CREATION_FAILED,
}
